name: "FAP: Build and lint"
on: [workflow_dispatch]
permissions:
  contents: "write"

jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    name: 'ufbt: Build'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          # Set to 'release' to build for latest published release version
          sdk-channel: release
      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
            tag_name: "${{ github.ref_name }}"
            release_name: "Release ${{ github.ref_name }}"
            draft: false
            prerelease: false
  
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
            upload_url: "${{ steps.create_release.outputs.upload_url }}"
            asset_path: ${{ steps.build-app.outputs.fap-artifacts }}
            asset_name: "pet_your_dolphin.fap"
            asset_content_type: "application/octet-stream"